In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('carprices.csv')

In [3]:
df

                Car Model  Mileage  Sell Price($)  Age(yrs)
0                  BMW X5    69000          18000         6
1                  BMW X5    35000          34000         3
2                  BMW X5    57000          26100         5
3                  BMW X5    22500          40000         2
4                  BMW X5    46000          31500         4
5                 Audi A5    59000          29400         5
6                 Audi A5    52000          32000         5
7                 Audi A5    72000          19300         6
8                 Audi A5    91000          12000         8
9   Mercedez Benz C class    67000          22000         6
10  Mercedez Benz C class    83000          20000         7
11  Mercedez Benz C class    79000          21000         7
12  Mercedez Benz C class    59000          33000         5

In [4]:
dummies = pd.get_dummies(df['Car Model'])

In [5]:
new_df = pd.concat([df,dummies],axis='columns')

In [6]:
new_df.drop(columns=['Car Model','Mercedez Benz C class'],inplace=True)

In [7]:
new_df

    Mileage  Sell Price($)  Age(yrs)  Audi A5  BMW X5
0     69000          18000         6    False    True
1     35000          34000         3    False    True
2     57000          26100         5    False    True
3     22500          40000         2    False    True
4     46000          31500         4    False    True
5     59000          29400         5     True   False
6     52000          32000         5     True   False
7     72000          19300         6     True   False
8     91000          12000         8     True   False
9     67000          22000         6    False   False
10    83000          20000         7    False   False
11    79000          21000         7    False   False
12    59000          33000         5    False   False

In [8]:
# transform true to 1 and false to 0

new_df[['Audi A5','BMW X5']] = new_df[['Audi A5','BMW X5']].apply(lambda x:x*1)

In [9]:
new_df

    Mileage  Sell Price($)  Age(yrs)  Audi A5  BMW X5
0     69000          18000         6        0       1
1     35000          34000         3        0       1
2     57000          26100         5        0       1
3     22500          40000         2        0       1
4     46000          31500         4        0       1
5     59000          29400         5        1       0
6     52000          32000         5        1       0
7     72000          19300         6        1       0
8     91000          12000         8        1       0
9     67000          22000         6        0       0
10    83000          20000         7        0       0
11    79000          21000         7        0       0
12    59000          33000         5        0       0

In [10]:
from sklearn.linear_model import LinearRegression

reg= LinearRegression()

In [19]:
x = new_df.drop(columns=['Sell Price($)'])
y = new_df['Sell Price($)']

In [20]:
reg.fit(x,y)

LinearRegression()

In [21]:
reg.predict([[45000,4,0,1]])

/home/soham/.local/lib/python3.10/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([30253.10988495])

In [22]:
from sklearn.metrics import mean_squared_error,mean_absolute_error

In [23]:
mse = mean_squared_error(new_df['Sell Price($)'],reg.predict(new_df[['Mileage','Age(yrs)','Audi A5','BMW X5']]))

In [24]:
mse

3447036.4477035077

In [25]:
mae = mean_absolute_error(new_df['Sell Price($)'],reg.predict(new_df[['Mileage','Age(yrs)','Audi A5','BMW X5']]))

In [27]:
mae

1566.686654505391

In [30]:
reg.predict([[67000,	6,	0	,0]])

/home/soham/.local/lib/python3.10/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([26183.72387884])

In [31]:
df.describe()

            Mileage  Sell Price($)   Age(yrs)
count     13.000000      13.000000  13.000000
mean   60884.615385   26023.076923   5.307692
std    19185.665055    8003.661021   1.652504
min    22500.000000   12000.000000   2.000000
25%    52000.000000   20000.000000   5.000000
50%    59000.000000   26100.000000   5.000000
75%    72000.000000   32000.000000   6.000000
max    91000.000000   40000.000000   8.000000

In [33]:
reg.score(x,y)

0.9417050937281082

In [34]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

In [65]:

df['Car Model'] = le.fit_transform(df['Car Model'])

In [66]:
df

    Car Model  Mileage  Sell Price($)  Age(yrs)
0           1    69000          18000         6
1           1    35000          34000         3
2           1    57000          26100         5
3           1    22500          40000         2
4           1    46000          31500         4
5           0    59000          29400         5
6           0    52000          32000         5
7           0    72000          19300         6
8           0    91000          12000         8
9           2    67000          22000         6
10          2    83000          20000         7
11          2    79000          21000         7
12          2    59000          33000         5

In [124]:
X = df.drop(columns=['Sell Price($)'])

In [125]:
print(X)

    Car Model  Mileage  Age(yrs)
0           1    69000         6
1           1    35000         3
2           1    57000         5
3           1    22500         2
4           1    46000         4
5           0    59000         5
6           0    52000         5
7           0    72000         6
8           0    91000         8
9           2    67000         6
10          2    83000         7
11          2    79000         7
12          2    59000         5

In [126]:
Y = df['Sell Price($)']

In [127]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(handle_unknown='ignore',sparse_output=False).set_output(transform='pandas')

In [128]:
cm = ohe.fit_transform(X[['Car Model']])
cm

    Car Model_0  Car Model_1  Car Model_2
0           0.0          1.0          0.0
1           0.0          1.0          0.0
2           0.0          1.0          0.0
3           0.0          1.0          0.0
4           0.0          1.0          0.0
5           1.0          0.0          0.0
6           1.0          0.0          0.0
7           1.0          0.0          0.0
8           1.0          0.0          0.0
9           0.0          0.0          1.0
10          0.0          0.0          1.0
11          0.0          0.0          1.0
12          0.0          0.0          1.0

In [129]:
# drop the last colum from cm

cm = cm.drop(columns=['Car Model_2'])

In [130]:
# rename cols of cm to Audi A5 and BMW X5

cm = cm.rename(columns={'Car Model_0':'Audi A5','Car Model_1':'BMW X5'})

In [131]:
cm

    Audi A5  BMW X5
0       0.0     1.0
1       0.0     1.0
2       0.0     1.0
3       0.0     1.0
4       0.0     1.0
5       1.0     0.0
6       1.0     0.0
7       1.0     0.0
8       1.0     0.0
9       0.0     0.0
10      0.0     0.0
11      0.0     0.0
12      0.0     0.0

In [132]:
X

    Car Model  Mileage  Age(yrs)
0           1    69000         6
1           1    35000         3
2           1    57000         5
3           1    22500         2
4           1    46000         4
5           0    59000         5
6           0    52000         5
7           0    72000         6
8           0    91000         8
9           2    67000         6
10          2    83000         7
11          2    79000         7
12          2    59000         5

In [133]:
X = pd.concat([X,cm],axis='columns')

In [134]:
X

    Car Model  Mileage  Age(yrs)  Audi A5  BMW X5
0           1    69000         6      0.0     1.0
1           1    35000         3      0.0     1.0
2           1    57000         5      0.0     1.0
3           1    22500         2      0.0     1.0
4           1    46000         4      0.0     1.0
5           0    59000         5      1.0     0.0
6           0    52000         5      1.0     0.0
7           0    72000         6      1.0     0.0
8           0    91000         8      1.0     0.0
9           2    67000         6      0.0     0.0
10          2    83000         7      0.0     0.0
11          2    79000         7      0.0     0.0
12          2    59000         5      0.0     0.0

In [135]:
X.drop(columns=['Car Model'],inplace=True)

In [136]:
reg2 = LinearRegression()

In [137]:
reg2.fit(X,Y)

LinearRegression()

In [138]:
reg2.predict([[45000,4,0,1]])

/home/soham/.local/lib/python3.10/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([30253.10988495])

In [139]:
reg2.score(X,Y)

0.9417050937281082